//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wantSora
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertResume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpertResume()
        {
            this.ExpertWorkList = new HashSet<ExpertWorkList>();
        }
    
        public int ResumeID { get; set; }
        public string Introduction { get; set; }
        public string WorksUrl { get; set; }
        public string ContactMethod { get; set; }
        public string ServiceMethod { get; set; }
        public string PaymentMethod { get; set; }
        public string Problem { get; set; }
        public Nullable<decimal> CommonPrice { get; set; }
        public Nullable<int> HistoricalViews { get; set; }
    
        public virtual Resume Resume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpertWorkList> ExpertWorkList { get; set; }
    }
}
