//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wantSora
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class ForumPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForumPost()
        {
            this.ForumPost1 = new HashSet<ForumPost>();
            this.ForumPostCategory = new HashSet<ForumPostCategory>();
            this.ForumPostComment = new HashSet<ForumPostComment>();
        }
    
        public int PostID { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string PostContent { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public byte Status { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> LikeCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumPost> ForumPost1 { get; set; }
        public virtual ForumPost ForumPost2 { get; set; }
        public virtual ForumStatus ForumStatus { get; set; }
        public virtual MemberAccount MemberAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumPostCategory> ForumPostCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumPostComment> ForumPostComment { get; set; }
    }
}
