//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wantSora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskList()
        {
            this.ApplicationList = new HashSet<ApplicationList>();
            this.CaseSkill = new HashSet<CaseSkill>();
            this.ExpertApplication = new HashSet<ExpertApplication>();
            this.MemberCollection = new HashSet<MemberCollection>();
            this.OrderDetail = new HashSet<OrderDetail>();
            this.TaskKeywordList = new HashSet<TaskKeywordList>();
            this.TaskPhoto = new HashSet<TaskPhoto>();
        }
    
        public int CaseID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> TaskNameID { get; set; }
        public string TaskTitle { get; set; }
        public string TaskDetail { get; set; }
        public Nullable<int> TeachToID { get; set; }
        public Nullable<int> WorkingHoursID { get; set; }
        public Nullable<int> PayFrom { get; set; }
        public Nullable<int> PayTo { get; set; }
        public Nullable<int> SalaryID { get; set; }
        public Nullable<int> TaskPlace { get; set; }
        public Nullable<int> TownID { get; set; }
        public Nullable<bool> WorkPlace { get; set; }
        public string Address { get; set; }
        public string RequiredNum { get; set; }
        public string TaskPeriod { get; set; }
        public string TaskStart { get; set; }
        public string TaskEnd { get; set; }
        public string Requirement { get; set; }
        public string HumanList { get; set; }
        public string LanguageRequired { get; set; }
        public Nullable<int> SkillRequiredID { get; set; }
        public Nullable<int> CertificateRequiredID { get; set; }
        public Nullable<bool> ServiceStatus { get; set; }
        public Nullable<int> StatusChangeReasonID { get; set; }
        public string PublishOrNot { get; set; }
        public string PublishStart { get; set; }
        public string PublishEnd { get; set; }
        public Nullable<int> CaseStatusID { get; set; }
        public Nullable<int> OnTop { get; set; }
        public string DataCreateDate { get; set; }
        public string DataModifyDate { get; set; }
        public string DataModifyPerson { get; set; }
        public Nullable<bool> IsExpert { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationList> ApplicationList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseSkill> CaseSkill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpertApplication> ExpertApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberCollection> MemberCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskKeywordList> TaskKeywordList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskPhoto> TaskPhoto { get; set; }
    }
}
